// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: demo.proto

#include "demo.pb.h"
#include "demo.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace demo {

static const char* Indexer_method_names[] = {
  "/demo.Indexer/DoWork",
};

std::unique_ptr< Indexer::Stub> Indexer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Indexer::Stub> stub(new Indexer::Stub(channel, options));
  return stub;
}

Indexer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_DoWork_(Indexer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Indexer::Stub::DoWork(::grpc::ClientContext* context, const ::demo::Empty& request, ::demo::WorkResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::demo::Empty, ::demo::WorkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DoWork_, context, request, response);
}

void Indexer::Stub::async::DoWork(::grpc::ClientContext* context, const ::demo::Empty* request, ::demo::WorkResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::demo::Empty, ::demo::WorkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DoWork_, context, request, response, std::move(f));
}

void Indexer::Stub::async::DoWork(::grpc::ClientContext* context, const ::demo::Empty* request, ::demo::WorkResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DoWork_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::demo::WorkResponse>* Indexer::Stub::PrepareAsyncDoWorkRaw(::grpc::ClientContext* context, const ::demo::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::demo::WorkResponse, ::demo::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DoWork_, context, request);
}

::grpc::ClientAsyncResponseReader< ::demo::WorkResponse>* Indexer::Stub::AsyncDoWorkRaw(::grpc::ClientContext* context, const ::demo::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDoWorkRaw(context, request, cq);
  result->StartCall();
  return result;
}

Indexer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Indexer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Indexer::Service, ::demo::Empty, ::demo::WorkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Indexer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::demo::Empty* req,
             ::demo::WorkResponse* resp) {
               return service->DoWork(ctx, req, resp);
             }, this)));
}

Indexer::Service::~Service() {
}

::grpc::Status Indexer::Service::DoWork(::grpc::ServerContext* context, const ::demo::Empty* request, ::demo::WorkResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace demo

